[package]
name = "locations-rs"
version = "0.1.0"
authors = ["Matěj Laitl <matej@laitl.cz>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
http = "0.1"
log = "0.4"
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
tide = "0.6"
tokio = { version = "0.2.11", features = ["macros", "rt-threaded"] }

[patch.crates-io]
tide = { git = "https://github.com/strohel/tide.git", branch = "intoresponse-for-result" }
