[package]
name = "locations-rs"
version = "0.1.0"
authors = ["Matěj Laitl <matej@laitl.cz>"]
edition = "2018"

[dependencies]
elasticsearch = { git = "https://github.com/strohel/elasticsearch-rs.git", branch = "port-from-reqwest-to-surf" }
async-std = { version = "1.5", features = ["attributes"]}
env_logger = "0.7"
http = "0.1"
log = "0.4"
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.48"
tide = "0.6"

[patch.crates-io]
tide = { git = "https://github.com/strohel/tide.git", branch = "intoresponse-for-result" }
