[package]
name = "locations-rs"
version = "0.1.0"
authors = ["Matěj Laitl <matej@laitl.cz>"]
edition = "2018"

[dependencies]
async-std = { version = "1.5", features = ["attributes"]}
env_logger = "0.7"
http = "0.1"
log = "0.4"
pretty_env_logger = "0.4"
tide = "0.6"
